### ISSUE TITLE
No fixes for FOUC SSR problem

### ISSUE THREAD

**Issue by soleimanidavoud** [nikandlv/nextjs-boilerplate-sass#2]
material-ui has FOUC problem we need this solution, thanks. :)
https://github.com/mui-org/material-ui/tree/master/examples/nextjs

**Comment by nikandlv** [comment]
Is this only related to material-ui or it needs to be fixed in general?

**Comment by nikandlv** [comment]
This only occurs when we use Material-UI
I will patch this in a new branch dedicated to the material-ui @soleimanidavoud
